CC = gcc
FLAGS = -Wall -g

TFS468:
cp //home/foaad/www/class/468/TFS468/libDisk.o //home/foaad/www/class/468/TFS468/libTinyFS.o //home/foaad/www/class/468/TFS468/*.h .
tests: tests.c
$(CC) $(CFLAGS) -o tests tests.c libDisk.o libTinyFS.o